# Generated by Django 5.2.5 on 2025-08-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
