# Generated by Django 5.2.5 on 2025-08-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pays_commission',
            field=models.BooleanField(default=True, verbose_name='Paga Comissão'),
        ),
    ]
