# Generated by Django 5.2.5 on 2025-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Alíquota Padrão de Imposto (%)')),
            ],
            options={
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
