# Generated by Django 5.2.5 on 2025-08-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('person_type', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('ie_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='IE / RG')),
                ('is_ie_exempt', models.BooleanField(default=False, verbose_name='IE Isento')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('B', 'Bloqueado')], default='A', max_length=1, verbose_name='Situação')),
                ('tax_regime', models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=20, null=True, verbose_name='Regime Tributário')),
                ('segment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento')),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Contato')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-mail')),
                ('nfe_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail para NFe')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Web Site')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('father_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Pai')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('mother_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF da Mãe')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Contatos')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Limite de Crédito')),
                ('customer_since', models.DateField(blank=True, null=True, verbose_name='Cliente Desde')),
                ('next_visit', models.DateField(blank=True, null=True, verbose_name='Próxima Visita')),
                ('payment_condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condição de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
