# Generated by Django 5.2.5 on 2025-08-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='pays_commission',
            field=models.BooleanField(default=False, verbose_name='Paga Comissão na Venda'),
        ),
    ]
