# Generated by Django 5.2.5 on 2025-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_pays_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Imposto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota de Imposto (%)'),
        ),
    ]
