# Generated by Django 5.2.5 on 2025-08-30 21:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_tax_amount_sale_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('SERVICE', 'Serviços')], default='SERVICE', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='sale',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condição de Pagamento'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['due_date'],
            },
        ),
    ]
